<?php

/**
 * BaseGivingRecord
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $year
 * @property integer $amount
 * 
 * @method integer      getYear()   Returns the current record's "year" value
 * @method integer      getAmount() Returns the current record's "amount" value
 * @method GivingRecord setYear()   Sets the current record's "year" value
 * @method GivingRecord setAmount() Sets the current record's "amount" value
 * 
 * @package    cfssf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGivingRecord extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('giving_record');
        $this->hasColumn('year', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('amount', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}