<?php

/**
 * BaseContent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property clob $body
 * @property integer $view_count
 * @property enum $recommend_level
 * @property integer $category_id
 * @property User $User
 * @property Doctrine_Collection $Comments
 * 
 * @method string              getTitle()           Returns the current record's "title" value
 * @method clob                getBody()            Returns the current record's "body" value
 * @method integer             getViewCount()       Returns the current record's "view_count" value
 * @method enum                getRecommendLevel()  Returns the current record's "recommend_level" value
 * @method integer             getCategoryId()      Returns the current record's "category_id" value
 * @method User                getUser()            Returns the current record's "User" value
 * @method Doctrine_Collection getComments()        Returns the current record's "Comments" collection
 * @method Content             setTitle()           Sets the current record's "title" value
 * @method Content             setBody()            Sets the current record's "body" value
 * @method Content             setViewCount()       Sets the current record's "view_count" value
 * @method Content             setRecommendLevel()  Sets the current record's "recommend_level" value
 * @method Content             setCategoryId()      Sets the current record's "category_id" value
 * @method Content             setUser()            Sets the current record's "User" value
 * @method Content             setComments()        Sets the current record's "Comments" collection
 * 
 * @package    cfssf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('content');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('body', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('view_count', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('recommend_level', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 0,
              1 => 1,
              2 => 2,
             ),
             'default' => 2,
             ));
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'category_id',
             'foreign' => 'id'));

        $this->hasMany('Comment as Comments', array(
             'local' => 'id',
             'foreign' => 'content_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}