<?php

/**
 * BaseGrantEvent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property clob $comment
 * @property integer $collector_id
 * @property integer $reviewer_id
 * @property integer $organization_id
 * @property Organization $Organization
 * @property Member $Member
 * 
 * @method clob         getComment()         Returns the current record's "comment" value
 * @method integer      getCollectorId()     Returns the current record's "collector_id" value
 * @method integer      getReviewerId()      Returns the current record's "reviewer_id" value
 * @method integer      getOrganizationId()  Returns the current record's "organization_id" value
 * @method Organization getOrganization()    Returns the current record's "Organization" value
 * @method Member       getMember()          Returns the current record's "Member" value
 * @method GrantEvent   setComment()         Sets the current record's "comment" value
 * @method GrantEvent   setCollectorId()     Sets the current record's "collector_id" value
 * @method GrantEvent   setReviewerId()      Sets the current record's "reviewer_id" value
 * @method GrantEvent   setOrganizationId()  Sets the current record's "organization_id" value
 * @method GrantEvent   setOrganization()    Sets the current record's "Organization" value
 * @method GrantEvent   setMember()          Sets the current record's "Member" value
 * 
 * @package    cfssf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGrantEvent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('grant_event');
        $this->hasColumn('comment', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('collector_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('reviewer_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('organization_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Organization', array(
             'local' => 'organization_id',
             'foreign' => 'id'));

        $this->hasOne('Member', array(
             'local' => 'reviewer_id',
             'foreign' => 'id'));
    }
}