<?php

/**
 * BaseUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $email
 * @property Doctrine_Collection $Organizations
 * 
 * @method string              getName()          Returns the current record's "name" value
 * @method string              getEmail()         Returns the current record's "email" value
 * @method Doctrine_Collection getOrganizations() Returns the current record's "Organizations" collection
 * @method User                setName()          Sets the current record's "name" value
 * @method User                setEmail()         Sets the current record's "email" value
 * @method User                setOrganizations() Sets the current record's "Organizations" collection
 * 
 * @package    cfssf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user');
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('email', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Organizations', array(
             'local' => 'id',
             'foreign' => 'category_id'));
    }
}