<?php

/**
 * BaseGrants
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property clob $body
 * @property integer $collector_id
 * @property integer $reviewer_id
 * @property integer $organization_id
 * @property Member $Member
 * 
 * @method clob    getBody()            Returns the current record's "body" value
 * @method integer getCollectorId()     Returns the current record's "collector_id" value
 * @method integer getReviewerId()      Returns the current record's "reviewer_id" value
 * @method integer getOrganizationId()  Returns the current record's "organization_id" value
 * @method Member  getMember()          Returns the current record's "Member" value
 * @method Grants  setBody()            Sets the current record's "body" value
 * @method Grants  setCollectorId()     Sets the current record's "collector_id" value
 * @method Grants  setReviewerId()      Sets the current record's "reviewer_id" value
 * @method Grants  setOrganizationId()  Sets the current record's "organization_id" value
 * @method Grants  setMember()          Sets the current record's "Member" value
 * 
 * @package    cfssf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGrants extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('grants');
        $this->hasColumn('body', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('collector_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('reviewer_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('organization_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Member', array(
             'local' => 'reviewer_id',
             'foreign' => 'id'));
    }
}