<?php

/**
 * BaseGivingRecord
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $year
 * @property integer $amount
 * @property integer $organization_id
 * @property Organization $Organization
 * 
 * @method integer      getYear()            Returns the current record's "year" value
 * @method integer      getAmount()          Returns the current record's "amount" value
 * @method integer      getOrganizationId()  Returns the current record's "organization_id" value
 * @method Organization getOrganization()    Returns the current record's "Organization" value
 * @method GivingRecord setYear()            Sets the current record's "year" value
 * @method GivingRecord setAmount()          Sets the current record's "amount" value
 * @method GivingRecord setOrganizationId()  Sets the current record's "organization_id" value
 * @method GivingRecord setOrganization()    Sets the current record's "Organization" value
 * 
 * @package    cfssf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGivingRecord extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('giving_record');
        $this->hasColumn('year', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('amount', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('organization_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Organization', array(
             'local' => 'organization_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}