<?php

/**
 * BaseOrganizations
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $engName
 * @property string $chnName
 * @property clob $reviewercomment
 * @property integer $collector_id
 * @property integer $reviewer_id
 * @property Member $Member
 * 
 * @method string        getEngName()         Returns the current record's "engName" value
 * @method string        getChnName()         Returns the current record's "chnName" value
 * @method clob          getReviewercomment() Returns the current record's "reviewercomment" value
 * @method integer       getCollectorId()     Returns the current record's "collector_id" value
 * @method integer       getReviewerId()      Returns the current record's "reviewer_id" value
 * @method Member        getMember()          Returns the current record's "Member" value
 * @method Organizations setEngName()         Sets the current record's "engName" value
 * @method Organizations setChnName()         Sets the current record's "chnName" value
 * @method Organizations setReviewercomment() Sets the current record's "reviewercomment" value
 * @method Organizations setCollectorId()     Sets the current record's "collector_id" value
 * @method Organizations setReviewerId()      Sets the current record's "reviewer_id" value
 * @method Organizations setMember()          Sets the current record's "Member" value
 * 
 * @package    cfssf
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOrganizations extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('organizations');
        $this->hasColumn('engName', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('chnName', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('reviewercomment', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('collector_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('reviewer_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Member', array(
             'local' => 'reviewer_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}