contact_person:
  class: sfDoctrineRouteCollection
  options:
    model:                ContactPerson
    module:               contact_person
    prefix_path:          /contact_person
    column:               id
    with_wildcard_routes: true

asset_record:
  class: sfDoctrineRouteCollection
  options:
    model:                AssetRecord
    module:               asset_record
    prefix_path:          /asset_record
    column:               id
    with_wildcard_routes: true

grantx:
  class: sfDoctrineRouteCollection
  options:
    model:                grantx
    module:               grantx
    prefix_path:          /grantx
    column:               id
    with_wildcard_routes: true

grant_event:
  class: sfDoctrineRouteCollection
  options:
    model:                GrantEvent
    module:               grant_event
    prefix_path:          /grant_event
    column:               id
    with_wildcard_routes: true

organization:
  class: sfDoctrineRouteCollection
  options:
    model:                Organization
    module:               organization
    prefix_path:          /organization
    column:               id
    with_wildcard_routes: true

member:
  class: sfDoctrineRouteCollection
  options:
    model:                Member
    module:               member
    prefix_path:          /member
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: home, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
