<?php

/**
 * GrantsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GrantsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GrantsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Grants');
    }
}