<?php

/**
 * GrantxTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GrantxTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GrantxTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Grantx');
    }
}