<?php

/**
 * GrantEventTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GrantEventTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GrantEventTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GrantEvent');
    }
}