<?php

/**
 * OrganizationsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrganizationsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrganizationsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Organizations');
    }
}