generator:
  class: sfDoctrineGenerator
  param:
    model_class:           grantx
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          grantx
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Grant List
        display: [id, =name, status, organization_id, collector_id, reviewer_id]
      filter:
        display: [id, name, status, organization_id, collector_id, reviewer_id]        
      form:    ~
      edit:    ~
      new:     ~
