generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Organization
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          organization
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [id, =eng_name, =chn_name, status, collector_id, reviewer_id]
      filter:
        display: [id, eng_name, chn_name, status, collector_id, reviewer_id]
      form:
        fields:
         hide: [created_at]
      edit:    ~
      new:     ~
