Member:
  columns:
    name: string(50)
    email: string(50)

Organization:
  actAs:
    Timestampable: ~
  columns:
    eng_name:
      type: string(255) 
      notnull: true
    chn_name: 
      type: string(255)    
    website:
      type: string(255)
    status:
      type: enum
      values: ['To be reviewed','Reviewed' ,'Complete']
      default: 'To be reviewer'
      notnull: true
    comment: clob
    collector_id:
      type: integer
      notnull: true
    reviewer_id: 
      type: integer    
  relations:
    Reviewer:
      class: Member
      onDelete: CASCADE
      local: reviewer_id
      foreign: id
      foreignAlias: ReviewedOrganizations
    Collector:
      class: Member
      onDelete: CASCADE
      local: collector_id
      foreign: id
      foreignAlias: CollectedOrganizations
 
Grantx:
  actAs:
    Timestampable: ~
  columns:
    name:
      type: string(255)
      notnull: true
    status:
      type: enum
      values: ['To be reviewed','Reviewed' ,'Complete']
      default: 'To be reviewed'
      notnull: true
    frequency:
      type: enum
      values: ['Yearly','Biannual','Dependent on Funds','Ongoing','Other']
      notnull: true
    attachment: blob
    comment: clob
    organization_id:
      type: integer
      notnull: true
    collector_id:
      type: integer
      notnull: true
    reviewer_id: 
      type: integer    
  relations:
    Reviewer:
      class: Member
      onDelete: CASCADE
      local: reviewer_id
      foreign: id
      foreignAlias: ReviewedGrantxs
    Collector:
      class: Member
      onDelete: CASCADE
      local: collector_id
      foreign: id
      foreignAlias: CollectedGrantxs
    
    Organization:
      onDelete: CASCADE
      local: organization_id
      foreign: id
      foreignAlias: Grants
 
AssetRecord:
  columns:
    year: integer
    amount: integer
    organization_id: integer
  relations:
    Organization:
      local: organization_id
      foreign: id
      foreignAlias: AssetRecords

GivingRecord:
  columns:
    year: integer
    amount: integer
    organization_id: integer
  relations:
    Organization:
      onDelete: CASCADE
      local: organization_id
      foreign: id
      foreignAlias: GivingRecords

ContactPerson:
  columns:
    name:
      type: string(255)
      notnull: true
    title: string(255)
    email: string(255)
    address: string(255)
    phone: string(255)
    organization_id: integer
  relations:
    Organization:
      onDelete: CASCADE
      local: organization_id
      foreign: id
      foreignAlias: ContactPersons
