Member:
  columns:
    name: string(50)
    email: string(50)

Organization:
  actAs:
    Timestampable:
      onInsert: true
  columns:
    engName:
      type: string(255) 
      notnull: true
      unique: true
    chnName: 
      type: string(255)    
      unique: true
    website:
      type: string(255)
    status:
      type: enum
      values: ['To be reviewed','Reviewed' ,'Complete']
      default: 'To be reviewer'
      notnull: true
    comment: clob
    collector_id:
      type: integer
      notnull: true
    reviewer_id: integer    
  relations:
    Member:
      local: collector_id
      foreign: id
      foreignAlias: CollectedOrganizations
    Member:
      local: reviewer_id
      foreign: id
      foreignAlias: ReviewedOrganizations

Grantx:
  actAs:
    Timestampable: ~
  columns:
    name:
      type: string(255)
      notnull: true
    status:
      type: enum
      values: ['To be reviewed','Reviewed' ,'Complete']
      default: 'To be reviewer'
      notnull: true
    frequency:
      type: enum
      values: ['Yearly','Biannual','Dependent on Funds','Ongoing','Other']
      notnull: true
    comment: clob
    collector_id: integer
    reviewer_id: integer
    organization_id: integer
  relations:
    Organization:
      local: organization_id
      foreign: id
      foreignAlias: GrantEvents
    Member:
      local: collector_id
      foreign: id
      foreignAlias: CollectedGrantEvents
    Member:
      local: reviewer_id
      foreign: id
      foreignAlias: ReviewedGrantEvents

AssetRecord:
  columns:
    year: integer
    amount: integer
    organization_id: integer
  relations:
    Organization:
      local: organization_id
      foreign: id
      foreignAlias: AssetRecords

GivingRecord:
  columns:
    year: integer
    amount: integer
    organization_id: integer
  relations:
    Organization:
      local: organization_id
      foreign: id
      foreignAlias: GivingRecords

ContactPerson:
  columns:
    name:
      type: string(255)
      notnull: true
    title: string(255)
    email: string(255)
    address: string(255)
    phone: string(255)
    organization_id: integer
  relations:
    Organization:
      local: organization_id
      foreign: id
      foreignAlias: ContactPersons
