Member:
  columns:
    name: string(50)
    email: string(50)

Organizations:
  actAs:
    Timestampable: ~
  columns:
    name: string(255)
    reviewercomment: clob
    collector_id: integer
    reviewer_id: integer
  relations:
    Member:
      local: collector_id
      foreign: id
      foreignAlias: CollectedOrganizations
    Member:
      local: reviewer_id
      foreign: id
      foreignAlias: ReviewedOrganizations


Grants:
  columns:
    body: clob
    collector_id: integer
    reviewer_id: integer
    organization_id: integer
  relations:
    Organization:
      local: organization_id
      foreign: id
      foreignAlias: Grants
    Member:
      local: collector_id
      foreign: id
      foreignAlias: CollectedGrants
    Member:
      local: reviewer_id
      foreign: id
      foreignAlias: ReviewedGrants
