Member:
  columns:
    name: string(50)
    email: string(50)

Organization:
  actAs:
    Timestampable: ~
  columns:
    engName: string(255)
    chnName: string(255)    
    website: string(255)
    status:
      type: enum
      values: ['To be reviewed','Reviewed' ,'Complete']
      default: 'To be reviewer'
    comment: clob
    collector_id: integer
    reviewer_id: integer    
  relations:
    Member:
      local: collector_id
      foreign: id
      foreignAlias: CollectedOrganizations
    Member:
      local: reviewer_id
      foreign: id
      foreignAlias: ReviewedOrganizations


GrantEvent:
  columns:
    comment: clob
    collector_id: integer
    reviewer_id: integer
    organization_id: integer
  relations:
    Organization:
      local: organization_id
      foreign: id
      foreignAlias: GrantEvents
    Member:
      local: collector_id
      foreign: id
      foreignAlias: CollectedGrantEvents
    Member:
      local: reviewer_id
      foreign: id
      foreignAlias: ReviewedGrantEvents
AssetRecord:
  columns:
    year: integer
    amount: integer
    organization_id: integer
  relations:
    Organization:
      local: organization_id
      foreign: id
      foreignAlias: AssetRecords
GivingRecord:
  columns:
    year: integer
    amount: integer
