User:
  columns:
    name: string(50)
    email: string(50)

Organizations:
  actAs:
    Timestampable: ~
  columns:
    name: string(255)
    reviewercomment: clob
    collector_id: integer
  relations:
    User:
      local: collector_id
      foreign: id
      foreignAlias: Organizations

Grants:
  columns:
    body: clob
    user_id: integer
    organization_id: integer
  relations:
    Organization:
      local: organization_id
      foreign: id
      foreignAlias: Grants
    User:
      local: user_id
      foreign: id
      foreignAlias: CollectedGrants
